### ISSUE TITLE
Misalignment of metadata in Batocera

### ISSUE THREAD

**Issue by wholee** [lehcimcramtrebor/es-theme-comicscrap#2]
![image](https://user-images.githubusercontent.com/7470680/169389347-92093fb7-be2b-4c9b-bd8d-3daabc790b9a.png)

Batocera Beta v34 2022/05/18
Raspberry Pi 4

As you can see on above picture, there is a misalignment of game metadata.
Theme was updated through Batocera's EmulationStation menu.

**Comment by lehcimcramtrebor** [comment]
![EmulationStation 20-05-2022 06-21-26-669](https://user-images.githubusercontent.com/59354081/169450114-f477682b-fdc8-42eb-95f6-f4fb233ae5ba.png)
As you can see there is no problem for me, so try with batocera stable version to see if it's beta issue.

**Comment by ChildishhAlbino** [comment]
This is still an issue on Batocera stable V34. I have updated and fully redownloaded the theme to no avail.

<img width="291" alt="batocera_version" src="https://user-images.githubusercontent.com/36402974/171980700-a2fa69ae-6a38-4dca-87e4-72fcd574aa29.png">
<img width="523" alt="issue" src="https://user-images.githubusercontent.com/36402974/171980703-91a063c9-7e00-42de-850e-f5f6d0e8fc70.png">

**Comment by lehcimcramtrebor** [comment]
batocera should automatically pos metadata after label: so in this case if a bug exist i have define manually x to godd position.. try update and give me back.

**Comment by ChildishhAlbino** [comment]
It's been updated. Looks much better. 



![20220604_155153.jpg](https://user-images.githubusercontent.com/36402974/171986528-439fab05-76a2-4e8c-b1c0-2b93c74cba2f.jpg)

**Comment by lehcimcramtrebor** [comment]
Fine, I close. Thank you.
